all: xyz 

xyz: main.o add.o adi.o break.o cma.o cmp.o dad.o dcr.o dcx.o debugger.o dexToHex.o execution.o findindex.o flags.o hexToDex.o inr.o inx.o jc.o jmp.o jnc.o jz.o jnz.o lda.o lhld.o lxi.o mov.o mvi.o  print.o programCounter.o registerNumber.o runProgram.o set.o shld.o sta.o stax.o step.o sub.o sui.o
validAddress.o validRegister.o xchg.o

main.o: main.cpp
	g++ -c main.cpp

add.o: ADD.cpp
	g++ -c ADD.cpp

adi.o: ADI.cpp
	g++ -c ADI.cpp

break.o: BREAK.cpp
	g++ -c BREAK.cpp

cma.o: CMA.cpp
	g++ -c CMA.cpp

cmp.o: CMP.cpp
	g++ -c CMP.cpp

dad.o: DAD.cpp
	g++ -c DAD.cpp

dcr.o: dcr.cpp
	g++ -c dcr.cpp

dcx.o: DCX.cpp
	g++ -c DCX.cpp

debugger.o: debugger.cpp
	g++ -c debugger.cpp

decToHex.o: decToHex.cpp
	g++ -c decToHex.cpp

execution.o: execution.cpp
	g++ -c execution.cpp

findindex.o: findIndex.cpp
	g++ -c findIndex.cpp

flags.o: flags.cpp
	g++ -c flags.cpp

hexToDex.o: hexToDex.cpp
	g++ -c hexToDex.cpp

inr.o: inr.cpp
	g++ -c inr.cpp

inx.o: INX.cpp
	g++ -c INX.cpp

jc.o: JC.cpp
	g++ -c JC.cpp

jmp.o: JMP.cpp
	g++ -c JMP.cpp

jnc.o: JNC.cpp
	g++ -c JNC.cpp

jnz.o: JNZ.cpp
	g++ -c JNZ.cpp

jz.o: JZ.cpp
	g++ -c JZ.cpp

lda.o: lda.cpp
	g++ -c lda.cpp

lhld.o: lhld.cpp
	g++ -c lhld.cpp

lxi.o: LXI.cpp
	g++ -c LXI.cpp

mov.o: mov.cpp
	g++ -c mov.cpp

mvi.o: mvi.cpp
	g++ -c mvi.cpp

print.o: PRINT.cpp
	g++ -c PRINT.cpp

programCounter.o: programCounter.cpp
	g++ -c programCounter.cpp

registerNumber.o: registerNumber.cpp
	g++ -c registerNumber.cpp

runProgram.o: runProgram.cpp
	g++ -c runProgram.cpp

set.o: SET.cpp
	g++ -c SET.cpp

shld.o: shld.cpp
	g++ -c shld.cpp

sta.o: sta.cpp
	g++ -c sta.cpp

stax.o: STAX.cpp
	g++ -c STAX.cpp

step.o: STEP.cpp
	g++ -c STEP.cpp

sub.o: SUB.cpp
	g++ -c SUB.cpp

sui.o: SUI.cpp
	g++ -c SUI.cpp

validAddress.o: validAddress.cpp
	g++ -c validAddress.cpp

validRegister.o: validRegister.cpp
	g++ -c validRegister.cpp

xchg.o: XCHG.cpp
	g++ -c XCHG.cpp
